-- todo.sql

CREATE TABLE TODO(
	TDNO NUMBER PRIMARY KEY,
	TDWRITER NVARCHAR2(200) NOT NULL,
	TDCONTENT CLOB,
	TDDATE TIMESTAMP DEFAULT SYSTIMESTAMP,
	TDYN CHAR(1) DEFAULT 'N' CHECK (TDYN IN ('Y', 'N'))
);

CREATE SEQUENCE SEQ_TODO;